security:
  encoders:
    App\Entity\User:
      algorithm: bcrypt

  providers:
    database_provider:
      entity:
        class: App\Entity\User
        property: username

  firewalls:
    main:
      pattern:    ^/
      anonymous: ~
      provider: database_provider
      form_login:
        login_path: /login
        check_path: /login
      logout:
        invalidate_session: true
        path: /logout
        target: /login

  access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #- { path: ^/register, roles: [ROLE_ADMIN, ROLE_MANAGER] }
    #- { path: ^/, roles: ROLE_USER }
    - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
