security:
  encoders:
    App\Entity\User:
      algorithm: bcrypt

  providers:
    db_provider:
      entity:
        class: App\Entity\User
        property: username

  firewalls:
    main:
      pattern:    ^/
      anonymous: ~
      provider: db_provider
