<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZSALUYY\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZSALUYY/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZSALUYY.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerZSALUYY\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerZSALUYY\srcProdProjectContainer(array(
    'container.build_hash' => 'ZSALUYY',
    'container.build_id' => 'e94ab93a',
    'container.build_time' => 1527837735,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZSALUYY');
