<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYb2LlDc\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYb2LlDc/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYb2LlDc.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYb2LlDc\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerYb2LlDc\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Yb2LlDc',
    'container.build_id' => '6595f85b',
    'container.build_time' => 1527709497,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerYb2LlDc');
