<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container50b6Fts\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container50b6Fts/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container50b6Fts.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container50b6Fts\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container50b6Fts\srcDevDebugProjectContainer(array(
    'container.build_hash' => '50b6Fts',
    'container.build_id' => 'b6a2a210',
    'container.build_time' => 1528062231,
), __DIR__.\DIRECTORY_SEPARATOR.'Container50b6Fts');
