<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\SecurityController:createAdminUser' => function () {
    return ($this->privates['service_locator.uNPUW1B'] ?? $this->load('getServiceLocator_UNPUW1BService.php'));
}, 'App\\Controller\\SecurityController:login' => function () {
    return ($this->privates['service_locator.LJvx72t'] ?? $this->load('getServiceLocator_LJvx72tService.php'));
}, 'App\\Controller\\UserAccountController:index' => function () {
    return ($this->privates['service_locator.Dsrf6N5'] ?? $this->load('getServiceLocator_Dsrf6N5Service.php'));
}, 'App\\Controller\\UserManagementController:registerAction' => function () {
    return ($this->privates['service_locator.nL1LxJC'] ?? $this->load('getServiceLocator_NL1LxJCService.php'));
}, 'App\\Controller\\SecurityController::createAdminUser' => function () {
    return ($this->privates['service_locator.uNPUW1B'] ?? $this->load('getServiceLocator_UNPUW1BService.php'));
}, 'App\\Controller\\SecurityController::login' => function () {
    return ($this->privates['service_locator.LJvx72t'] ?? $this->load('getServiceLocator_LJvx72tService.php'));
}, 'App\\Controller\\UserAccountController::index' => function () {
    return ($this->privates['service_locator.Dsrf6N5'] ?? $this->load('getServiceLocator_Dsrf6N5Service.php'));
}, 'App\\Controller\\UserManagementController::registerAction' => function () {
    return ($this->privates['service_locator.nL1LxJC'] ?? $this->load('getServiceLocator_NL1LxJCService.php'));
})));
